### ISSUE TITLE
how we get to know that from which account(google account) we authorized 

### ISSUE THREAD

**Issue by enestdharam** [googleads/googleads-dotnet-lib#110]
Hello,
I am using asp.net web application to record conversions on google adwords account.I am using oauth2.0 flow to authorize the user's accounts (google account). I want to know fee things regarding this flow:

How I can get refresh token every-time I authorize the same google account
Is google authorization API returns any unique parameter or code for authorized account (google account), through which I can identify that this user previously authorized or not
If Point 1 is not possible: So is there any way or unique parameter to find that this account is already authorized for my app. So I can use the previous token that I get the first time for that account

Thanks

**Comment by AnashOommen** [comment]
I'm guessing that you want to login a user, and then identify what accounts this user has access to. If that's not the case, pls respond and I'll help you out.

I recommend a flow like this in your ASP.NET application:

1. Login your user (using your local username / password).
2. If this user has a RefreshToken stored against their profile, then do nothing. Otherwise, take them through the oAuth2 flow. There's a state parameter (https://github.com/googleads/googleads-dotnet-lib/blob/master/examples/AdWords/CSharp/OAuth/OAuthLogin.aspx.cs#L50) That OAuth2 provides so that you can track a user between the time you redirect them to Google site, and then back.
3. Make a call to CustomerService.get. This will give all the accounts that the user has access to. This list tends to change over time, so it is probably not worth saving this value in the local database for long periods of time.

https://developers.google.com/adwords/api/docs/guides/accounts-overview#customerservice

4. Next, check if this is a manager account. You can examine the Customer:: canManageClients field. If yes, use ManagedCustomerService.get to retrieve the account hierarchy. https://github.com/googleads/googleads-dotnet-lib/blob/91787e1a34f86fb2dfe3df4b3edeb546ef460542/examples/AdWords/CSharp/v201609/AccountManagement/GetAccountHierarchy.cs

Hope this helps?

**Comment by enestdharam** [comment]
@AnashOommen 
I have already followed these steps that you mentioned above.
I need how I can get refresh token every-time I authorize the same google account.
Is google authorization API returns any unique parameter or code for authorized account (google account), through which I can identify that this user previously authorized or not.
