### ISSUE TITLE
App.config.transform doesn't work in .NET Core projects

### ISSUE THREAD

**Issue by grivescorbett** [googleads/googleads-dotnet-lib#139]
With .NET standard projects, when you add a nuget reference to a project, the App.config is auto populated with the correct fields. This isn't relevant to / doesn't happen in .NET core projects.

**Comment by rfrancisco** [comment]
In our projects we don't even have App.config files since the expected way to to this in .Net core is to use the appsettings.json files. It would be great if you could remove this dependency on App.config files.

**Comment by AnashOommen** [comment]
While we can't remove support for App.config due to users still depending on it, adding support for appsettings.json should be fairly straightforward. Could you pls file a new bug for it?

Also, feel free to file FRs for .NET Core, we'd be happy to take a look at them now that we have basic .NET Core support for the client libraries.

**Comment by AnashOommen** [comment]
@rfrancisco I added Issue #157 for your request. @grivescorbett @christopherseeley the original issue is really a .NET Core WAI issue, though there's a FR for it: https://github.com/aspnet/Home/issues/2019.

**Comment by AnashOommen** [comment]
I'm closing this issue for now as not feasible, feel free to reopen if you think there's a way to address this.
