### ISSUE TITLE
Support other configuration sources than App.config...

### ISSUE THREAD

**Issue by AnashOommen** [googleads/googleads-dotnet-lib#157]
App.config is no longer the preferred configuration mechanism in .NET Core applications, so we should allow other configuration methods.

**Comment by otykier** [comment]
Not sure where to report this, but it looks like this fix re-introduced the dependency on System.Configuration, which was previously removed in issue #127.

This means that we get dependency errors when running under .NET Standard 2.0 and have to stay at v23.2.0 (or any build that uses v. 9.0.1 or v. 9.0.0 of Google.Ads.Common).

**Comment by christopherseeley** [comment]
Are you using the nuget packages? Do you have more details? I just created a test .NET Core application and had no dependency issues.

**Comment by otykier** [comment]
We're trying to create an Azure Function (v. 2) that uses Google.Dfp from nuget. We get the following error:
```
System.Private.CoreLib: Exception while executing function: Util_GoogleDFP_GetData.
System.Configuration.ConfigurationManager: Configuration system failed to initialize.
System.Configuration.ConfigurationManager: Unrecognized configuration section 
system.serviceModel.
(C:\Users\xxx\AppData\Local\AzureFunctionsTools\Releases\2.1.0\cli\func.dll.config line 204).
```
Turns out this is not a general issue in .NET Core, but Azure Functions unfortunately [no longer supports ConfigurationManager](https://blog.jongallant.com/2018/01/azure-function-config/). Please ignore my previous comment as the issue seems to be unrelated to the System.Configuration dependency.

To work around, I guess we would have to change Google.Ads.Common to use the ASPNET Core Configuration system as described in the link above, but I am unsure of the impact of this in the Google.Ads.Common codebase, and whether this would at all be feasible.

**Comment by AnashOommen** [comment]
You could pass an IConfigurationRoot as constructor to DfpAppConfig. The keys should be the same as what you see in App.config (e.g. NetworkCode, ApplicationName, etc.)

So something like this should work:

```
IConfigurationRoot configRoot = ...
DfpAppConfig config = new DfpAppConfig(configRoot);
DfpUser user = new DfpUser(config);
```
