### ISSUE TITLE
LabelType Enumeration

### ISSUE THREAD

**Issue by bbatton** [googleads/googleads-dotnet-lib#167]
I get the error INVALID_LABEL_TYPE when doing an ADD operation on the LabelService when not setting the LabelType on the Label Object. I have looked at the docs and it shows that I shouldn't have to pass a type and there are no types enumerated on the LabelType Class. The doc even refers to Label.Type and not Label.LabelType. Am I missing something?

**Comment by AnashOommen** [comment]
Try using TextLabel instead of Label.

See https://github.com/googleads/googleads-dotnet-lib/blob/7227298243a681f4b976e4044940de3230faf561/tests/AdWords/v201710/TestUtils.cs#L144 for an example.

Re: Label.Type v/s Label.LabelType - C# doesn't allow dots in property or field names. E.g. the following code is syntactically invalid.

```c#
class Label {
  public string Label.Type { get; set; }
}
```
Instead, it is generated like this:

```c#
class Label {
  [System.Xml.Serialization.XmlElementAttribute("Label.Type", Order = 4)]
  public string LabelType { get; set; }
}
```
