### ISSUE TITLE
XML Exception from ManagedCustomerService 

### ISSUE THREAD

**Issue by aukevin** [googleads/googleads-dotnet-lib#196]
Hi,

I'm getting an XML exception when making a get request to the ManagedCustomerService in C#.
It looks like the exception appears in AdWords API code:

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Google.Api.Ads.AdWords.v201809.ManagedCustomerServiceInterface.get(Selector serviceSelector)

System.ServiceModel.CommunicationException: Error in deserializing body of reply message for operation 'get'. --->
System.InvalidOperationException: There is an error in XML document (1, 87373). --->
System.Xml.XmlException: The byte 0x08 is not valid at this location.  Line 1, position 87373.

Is there a workaround?

Best,
Kevin

[Repost from AdWords API Forum]: https://groups.google.com/forum/#!topic/adwords-api/k07nVdUpN7Q]

**Comment by AnashOommen** [comment]
Hi Kevin, 

Could you try capturing the logs following the instructions at https://github.com/googleads/googleads-dotnet-lib/wiki/How-to-capture-SOAP-messages and then drop me an email at adwordapi-support@google.com? Most likely this is something malformed in the response itself, so I'll close this issue here, and reopen it if this is indeed a client library issue.

Tx
Anash
