### ISSUE TITLE
Support asynchronous calls in services

### ISSUE THREAD

**Issue by AnashOommen** [googleads/googleads-dotnet-lib#2]
Originally reported at https://github.com/googleads/googleads-adwords-dotnet-lib/issues/20

Hello Anash,
i would like to ask, how much effort would it be to to support async call. Or how it could be done to have something like this:
service.getAsync(selector)

The main reason actually is that mono is having some serious performance/locking/threading troubles on making simultaneously many concurrent synchronous requests.

**Comment by Zweitze** [comment]
Also consider asynchronous reports - that would be useful!

**Comment by franckyj** [comment]
I know this issue is closed, but why isn't this being developed? It would be huge to everybody.

**Comment by AnashOommen** [comment]
Actually, it isn't closed, it was marked as duplicate to https://github.com/googleads/googleads-dotnet-lib/issues/2, which is still open.

We didn't develop this earlier since we were on .NET 2.0 and System.Web.Services when this FR came in. No tasks, so async was pretty difficult to implement. Now that we are on .NET 4.5.2 (and soon, .NET Core), we will revisit this FR. Just waiting for the .NET Core change to go live.

**Comment by franckyj** [comment]
You're right, the other one is closed.

I'm just eager to have that capability. I could use the tool referenced in the other issue but I don't like the idea of manually recompiling the sources every time we update the lib. Also, since `Task`s have been there for quite a time now I though all the methods would have async counterpart by now.

If it's coming soon I can wait a little longer.

**Comment by AnashOommen** [comment]
Fixed in v23.6.0
