### ISSUE TITLE
Problem whit  refresh access token after update api version 201809

### ISSUE THREAD

**Issue by chesiri** [googleads/googleads-dotnet-lib#205]
After updating to version 201809, my application returns the following error:
```
Google.Api.Ads.Common.Lib.AdsOAuthException: Failed to refresh access token. --->  Google.Apis.Auth.OAuth2.Responses.TokenResponseException: 
Error:"invalid_client", Description:"The OAuth client was not found.", Uri:""
```

I tried to generate new update token but it did not work
Any idea?
I need help please.

**Comment by bbatton** [comment]
Have you double checked your app.config file for issues? If you update through nugget from a previous version it will append all the setup info into the app.config file even if it already exists. When that happens it will cause this same type of error to occur since it is reading the last config entry which is null on append.

**Comment by chesiri** [comment]
yes, the problem was app.config file.
I reversed the changes in the app.config file and the problem was fixed
thanks
