### ISSUE TITLE
Missing package from nuget

### ISSUE THREAD

**Issue by LaTanase** [googleads/googleads-dotnet-lib#247]
Hello! 

The latest version, the only one that is not deprecated yet, is missing from nuGet. Would be possible for you to publish it?

Thank you!

**Comment by LaTanase** [comment]
Hello!

Here https://github.com/googleads/googleads-dotnet-lib/releases the version 24.19.0 is marked as deprecated. Also some of the features thrown AdWordsApiException in 24.19.0. Can come back with the full error message if needed.

**Comment by AnashOommen** [comment]
Ah, I see. That "deprecation" is meant for Google.Dfp. No functionality has changed in Google.AdWords since v24.1.0, so you can stay on any one of the library after that version for now.

That said, the AdWords API itself has gone away, so it should start failing for you completely soon (if not already). See https://ads-developers.googleblog.com/2022/05/adwords-api-has-officially-sunset.html.

**Comment by LaTanase** [comment]
Thank you for your responses! Thought that it has some improvements on the AdWords. Will proceed to change to the new API.

**Comment by AnashOommen** [comment]
While migrating, please email googleadsapi-support@google.com with any questions you may have. It is easier to answer it that way instead of bugs on GitHub. 

For any library-specific issues, file an issue at https://github.com/googleads/google-ads-dotnet.
