### ISSUE TITLE
Issue to get ErrorList from BatchJobService

### ISSUE THREAD

**Issue by jbielsa-jot** [googleads/googleads-dotnet-lib#57]
Hello!!

When I try to execute the method BatchJobUtilites.Download(downloadUrl) to get the error list with a BatchJob in status CANCELED, throws an exception with a message "Invalid Primitive JSON"

Thanks

**Comment by AnashOommen** [comment]
Hi,

This should work with the latest release (18.18.0), but let me know if you still face issues.

**Comment by jbielsa-jot** [comment]
Sorry, with the latest release (18.18.0) I can't create the object BatchJobUtilites. It throws a StackOverflowException. Any thoughts? Thanks for your help.

**Comment by jbielsa-jot** [comment]
Hi Anash, how are you?

I've been running some additional tests and I think I've pinpointed the issue. I've observed that on many (not all) ocassions the UploadChunk procedure in BatchJobUtilities.cs hangs at a RequestStream event:

```c#
using (Stream requestStream = request.GetRequestStream())
```

Just to clarify, I've run these tests with the code modified as I indicated in my previous comment. Any thoughts?

**Comment by AnashOommen** [comment]
Looks like there is some handle leak? I could take another look once I push an updated version. That way you can run the utility class and debug things further.

**Comment by jbielsa-jot** [comment]
Thank you Anash. Please keep us up to speed with any developments, this module is very important for our development team.

**Comment by AnashOommen** [comment]
Could you pls try with the latest library and let me know if this is still an issue?

**Comment by jbielsa-jot** [comment]
Hi Anash, thanks for getting back to me. The issue (with the Class constructor) seems to be working OK, thank your for that. For some reason though I keep running into the error I mentioned in my [previous message](https://github.com/googleads/googleads-dotnet-lib/issues/57#issuecomment-158903208) (the UploadChunk procedure hangs at a RequestStream event). Any idea what could be happening?

Thanks! Regards.

**Comment by AnashOommen** [comment]
Could you share a code snippet that can probably replicate this issue? I'll independently try to replicate this at my end.

**Comment by jbielsa-jot** [comment]
Hi Anash,

I've been running some tests, let me explain briefly: after obtaining a BatchJobService and the BatchJob object, my code then calls the oBatchJobUtilities.Upload function, where it eventually hangs. I've been trying to determine the cause of this issue, and I found that the program hangs at [line 254](https://github.com/googleads/googleads-dotnet-lib/blob/master/src/AdWords/Util/BatchJob/v201509/BatchJobUtilities.cs#L254) the **third time** it loops through this code.

In order to replicate the issue, try to create three batch jobs and see if you obtain the same results. Maybe there's an issue with the request object when more than two requests have been made?

Thanks, best regards.

**Comment by AnashOommen** [comment]
Ah, okay, that sounds familiar. .NET's HTTP connection manager has a built-in default limit of 2 HTTP concurrent connections, it dates back to the Internet Explorer 6(?) days.

To override it, your Main() method should have a call like:

System.Net.ServicePointManager.DefaultConnectionLimit = 100;

You typically don't run into this limit because a typical API call takes a few hundred ms for roundtrip. Uploading a batchjob payload of few hundred MBs take longer.

**Comment by jbielsa-jot** [comment]
Hi Anash, 
Sometimes the Batchjobs remain in a "cancelled" status with null values for properties 'processingErrors' and 'downloadUrl'. I don't know why this is happening. 
I have several examples with specific identifiers (clientCustomerId and BatchJobId), would it be possible to look into this further?

Thanks

**Comment by AnashOommen** [comment]
Apologies for the delay. Please post a task ID or two and I'll look up the logs. This is most probably an issue on the server side.

**Comment by jbielsa-jot** [comment]
Hi Anash, no worries about the delay. Here's an example task IDs:
1144953 or 1091929
If you need the account IDs, I can send them to you via email.
Thanks, regards

**Comment by AnashOommen** [comment]
I've asked the team to take a look at the logs. And apologies for the delay, my github notifications were being sent to another account that is no longer monitored.

**Comment by jbielsa-jot** [comment]
Hi Anash, I've been trying with latest version of .NET API and AdWords (v201601) and I observed that I can't run the upload operation because I get an error (403).

In version (v201509) the URL to upload operations starts with (https://www.googleapis.com/....) and works fine, 
but with the latest version (v201601) the URL starts with (https://batch-job-upload-prod-ebe9b43.storage.googleapis.com/....), resulting in an error.

Let me know if this is something that can be fixed on my side or an update is needed. Thanks

**Comment by AnashOommen** [comment]
In v201601, you need to make an additional call to exchange the bulk upload
URL for a resumable upload URL. The relevant change in code is this line:

https://github.com/googleads/googleads-dotnet-lib/blob/master/examples/AdWords/CSharp/v201601/CampaignManagement/AddCompleteCampaignsUsingBatchJob.cs#L163

Cheers,
Anash

On 02/12/16 03:59:42 notifications@github.com wrote:

Hi Anash, I've been trying with latest version of .NET API and AdWords
(v201601) and I observed that I can't run the upload operation because I
get an error (403).

In version (v201509) the URL to upload operations starts with (
https://www.googleapis.com/....) and works fine,
but with the latest version (v201601) the URL starts with (
https://batch-job-upload-prod-ebe9b43.storage.googleapis.com/....),
resulting in an error.

Let me know if this is something that can be fixed on my side or an update
is needed. Thanks

—
Reply to this email directly or view it on GitHub
<https://github.com/googleads/googleads-dotnet-lib/issues/57#issuecomment-183240222>
.

**Comment by jbielsa-jot** [comment]
Ok Anash. Thanks a lot. With "resumable upload url" it works well!!! My comment was removed because I saw later in the example that detail.
Next week I'll try with the latest version (v201601) several times and give you a feedback.

Thanks

**Comment by jbielsa-jot** [comment]
Hi Anash. Yesterday I saw a batch job with ID 1268637 in canceled status. This week I read in Adwords API forum there was a problem with long time in Awaiting_File status, but now is fixed.

**Comment by AnashOommen** [comment]
Closing this issue for now, since the original issue was fixed a while back. Feel free to open a new issue if you need more help.
