### ISSUE TITLE
Authentication OAuth2 with wsdl.exe

### ISSUE THREAD

**Issue by docatram** [googleads/googleads-dotnet-lib#67]
Dear all,
I need to build a .dll through wsdl.exe and csc commands to reference a web service using OAuth2 authentication. Unfortunately, when I build the .dll in this way, I can just specify a username and a password (through /u and /p parameters) for my webservice, but I cannot specify the OAuth2 token for it. 
These are the steps I used to build the .dll that reference the web service:  
- step 1.
	  "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0a\bin\x64\wsdl.exe" /l:cs /protocol:SOAP http://AAA.BBB.CCC.DDD:XXX/SomeService?wsdl /u:myUserName /p:myPassword
- step 2.
	  c:\windows\microsoft.net\Framework\v3.5\csc /t:library /r:System.Web.Services.dll /r:System.Xml.dll SomeService.cs

Someone can help me to add some code lines in .cs file generated by wsdl.exe command to allow the calls to this webservice (that are performed through the .dll generated by wsdl.exe and csc commands) to be authenticated?

**Comment by AnashOommen** [comment]
If you are using AdWords API, use this library instead of generating raw stubs. If you are using some other API, then you'd need to override the <code>SoapHttpClientProtocol::GetWebRequest</code> method and add a <code>Authorization: Bearer access_token</code> HTTP header to the outgoing request. To generate access token, use a library like http://dotnetopenauth.net/.
