### ISSUE TITLE
BatchJob.downloadUrl is not populated

### ISSUE THREAD

**Issue by jsloyan** [googleads/googleads-dotnet-lib#74]
The C# example "AddCompleteCampaignsUsingBatchJob" successfully completes the job, with no processing errors, but the downloadUrl property is null.  We are seeing these results with v201509 and v201601 of the API (versions 18_17_0 and 18_22_0 of the client library).

**Comment by AnashOommen** [comment]
The selector needs to add a few more fields. See the Java example for details on the missing fields.

https://github.com/googleads/googleads-java-lib/blob/master/examples/adwords_axis/src/main/java/adwords/axis/v201601/campaignmanagement/AddCompleteCampaignsUsingBatchJob.java#L171

I'll get this fixed in the next library push.

**Comment by AnashOommen** [comment]
This is fixed in v18.23.0
