### ISSUE TITLE
Soap log truncated

### ISSUE THREAD

**Issue by cpicou** [googleads/googleads-dotnet-lib#76]
Hello,
I'm trying to log SOAP request and sometimes, the xml body is truncated. I don't think it's because of the size, because it's on a small request (mutate with an ADD operation on a campaign) and I have some bigger request that are not truncated.
Here a sample
[truncated.txt](https://github.com/googleads/googleads-dotnet-lib/files/153220/truncated.txt)

And my .config (only the trace part)
[app.config.txt](https://github.com/googleads/googleads-dotnet-lib/files/153229/app.config.txt)

I've managed to obtain what I want with the System.NET trace but it's very verbose.

Thank you

**Comment by AnashOommen** [comment]
I think this was done on purpose, because when operating under a batched mode, the class splits up the payload into smaller chunks and uploads them one by one. In this case, the byte array might be misaligned if the library tries to print the byte response as a string.

I agree that it might make sense to just log the whole payload once and then don't log the parts later. I'll discuss with the rest of the team and make a change for the next release.

**Comment by AnashOommen** [comment]
Fixed in v22.3.0.
