### ISSUE TITLE
Decryption failure when downloading reports

### ISSUE THREAD

**Issue by stewart-r** [googleads/googleads-dotnet-lib#89]
We are (occasionally) seeing the following error message when trying to download reports. The error is intermittent in that the same report can sometimes trigger the error and sometimes work as expected.

> Google.Api.Ads.Common.Util.Reports.AdsReportsException: Failed to download report. See inner exception for more details. ---> System.IO.IOException: The decryption operation failed, see inner exception. ---> System.ComponentModel.Win32Exception: The specified data could not be decrypted
>    --- End of inner exception stack trace ---
>    at System.Net.GZipWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 size)
>    at Google.Api.Ads.Common.Util.MediaUtilities.CopyStreamWithPreview(Stream sourceStream, Stream targetStream, Int32 maxPreviewBytes)
>    at Google.Api.Ads.Common.Util.Reports.ReportResponse.Download()
>    --- End of inner exception stack trace ---
>    at Google.Api.Ads.Common.Util.Reports.ReportResponse.Download()

**Comment by AnashOommen** [comment]
Could you pls try replicating this issue while routing the request through Fiddler? The instructions are here: https://github.com/googleads/googleads-dotnet-lib/wiki/How-to-capture-SOAP-messages#option-2-use-fiddler

This will let me figure out if this is an issue at the library side, or due to a bad payload coming back from the server.
